module.exports = {
  users: require("./users"),
  profilesWaiting: require("./profilesWaiting"),
  solution: require("./solution"),
  courses: require("./courses"),
  awards: require("./awards"),
  discipline: require("./discipline"),
  salary: require("./salary"),
  settings: require("./settings"),
  systemSalary: require("./systemSalary"),
  departments: require("./department"),
  news: require("./news"),
  workOverTime: require("./workOverTime"),
  documents: require("./documents"),
  typeOfDocuments: require("./typeOfDocuments"),
  contract: require("./contract"),
  positions: require("./positions"),
  absence: require("./absence"),
  courseYear: require("./courseYear"),
  notifies: require("./notifies"),
  newsCategory: require("./newsCategory")
};
